language: python

python:

  - "3.6"

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc73
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'gcc-7', 'gfortran-7','libffi-dev']
      env:
        - CXX='g++-7'
        - CC='gcc-7'
        - FC='gfortran-7'
      python: 3.6

install:
  - pip install -r requirements.txt --upgrade
  - python setup.py build


script:
  - cd pysus/utilities
  - python _build_readdbc.py
  - python --version
  - cd ../tests
#  - nosetests
