name: env-pysus
channels:
  - conda-forge
  - nodefaults
dependencies:
  - docker-compose
  - jupyterlab 
  - nodejs
  - cffi>=1.0.0
  - dbfread
  - geocoder
  - requests
  - fastparquet
  - geopandas
  - dask
  - wget
  - xarray
  - elasticsearch
  - pyarrow
  # dev
  - pip
  - flake8
  - coverage
  - sphinx
  - pandas
  - pytest
  - pytest-cov
  - pre-commit
  - numba
  - pip:
    - nbmake
    - facets-overview
    - pysus
